# Copyright (C) 2025 Luis González Fernández
# SPDX-License-Identifier: GPL-3.0-or-later

"""Generate the code-derived reference docs under docs/reference/.

Single source of truth for the API surface, CLI, configuration, tools and SSE
events is the CODE — this script extracts it and writes Markdown. CI re-runs it
and fails if the committed files differ (see .github/workflows/docs.yml), so the
reference docs can never drift from the application.

Usage:  python scripts/gen_docs.py      # rewrites docs/reference/*.md
"""

from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
REFDIR = ROOT / "docs" / "reference"
SRC = ROOT / "src" / "agents_discussion"

BANNER = (
    "<!-- GENERATED by scripts/gen_docs.py — DO NOT EDIT BY HAND.\n"
    "     Run `python scripts/gen_docs.py` and commit the result. -->\n"
)


def _write(name: str, body: str) -> None:
    REFDIR.mkdir(parents=True, exist_ok=True)
    (REFDIR / name).write_text(BANNER + "\n" + body.rstrip() + "\n", encoding="utf-8")


def _type_name(annotation: object) -> str:
    if annotation is None:
        return "—"
    name = getattr(annotation, "__name__", None)
    if name:
        return name
    return str(annotation).replace("typing.", "")


# ── REST API ────────────────────────────────────────────────────────────────
def gen_api() -> set[str]:
    from agents_discussion.web import app

    rows = []
    paths: set[str] = set()
    for route in app.routes:
        methods = getattr(route, "methods", None)
        path = getattr(route, "path", None)
        if not methods or not path:
            continue  # skip static Mount and websockets
        if path != "/" and not path.startswith("/api/"):
            continue  # skip FastAPI's built-in /docs, /redoc, /openapi.json
        verbs = sorted(m for m in methods if m not in {"HEAD", "OPTIONS"})
        for verb in verbs:
            rows.append((path, verb))
        paths.add(path)
    rows.sort(key=lambda r: (r[0], r[1]))
    lines = ["# REST API", "", "| Method | Path |", "|---|---|"]
    lines += [f"| `{verb}` | `{path}` |" for path, verb in rows]
    _write("api.md", "\n".join(lines))
    return paths


# ── CLI ───────────────────────────────────────────────────────────────────────
def gen_cli() -> None:
    from agents_discussion.cli import build_parser

    help_text = build_parser().format_help().rstrip()
    body = f"# CLI: `agents-discuss`\n\n```text\n{help_text}\n```"
    _write("cli.md", body)


# ── Configuration (env vars) ──────────────────────────────────────────────────
def gen_config() -> set[str]:
    from agents_discussion.config import Settings

    aliases: set[str] = set()
    rows = []
    for info in Settings.model_fields.values():
        alias = info.alias or "—"
        aliases.add(alias)
        default = info.default
        if default is None or repr(default) == "PydanticUndefined":
            default_str = "(computed)" if info.default_factory else "—"
        else:
            default_str = f"`{default!r}`"
        rows.append((alias, _type_name(info.annotation), default_str))
    rows.sort(key=lambda r: r[0])
    lines = [
        "# Configuration (environment variables)",
        "",
        "Set via environment variables or a `.env` file (see `.env.example`).",
        "",
        "| Variable | Type | Default |",
        "|---|---|---|",
    ]
    lines += [f"| `{alias}` | {typ} | {default} |" for alias, typ, default in rows]
    _write("configuration.md", "\n".join(lines))
    return aliases


# ── Tools (ReAct) ─────────────────────────────────────────────────────────────
def gen_tools() -> set[str]:
    from agents_discussion.tools import _ALL_TOOLS

    names: set[str] = set()
    lines = ["# Diagnostic tools (ReAct)", ""]
    for tool in sorted(_ALL_TOOLS, key=lambda t: t.name):
        names.add(tool.name)
        summary = (tool.description or "").strip().splitlines()[0] if tool.description else ""
        lines.append(f"- **`{tool.name}`** — {summary}")
    _write("tools.md", "\n".join(lines))
    return names


# ── SSE event types ───────────────────────────────────────────────────────────
_EVENT_RE = re.compile(r'"type":\s*"([a-z][a-z_]+)"')


def scan_event_types() -> set[str]:
    found: set[str] = set()
    for fname in ("graph.py", "runtime.py", "web.py"):
        text = (SRC / fname).read_text(encoding="utf-8")
        found.update(_EVENT_RE.findall(text))
    return found


def gen_events() -> set[str]:
    events = scan_event_types()
    lines = ["# SSE event types", "", "Events streamed over `GET /api/runs/{id}/events`:", ""]
    lines += [f"- `{ev}`" for ev in sorted(events)]
    _write("events.md", "\n".join(lines))
    return events


def main() -> None:
    import agents_discussion

    gen_api()
    gen_cli()
    gen_config()
    gen_tools()
    gen_events()
    print(f"Generated docs/reference/*.md for agents-discussion v{agents_discussion.__version__}")


if __name__ == "__main__":
    main()
